name: Windows ARM64 GCC Build gfortran

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: # Enables the manual trigger button

jobs:
  build:
    # Use the official GitHub-hosted native Windows 11 ARM64 runner
    runs-on: windows-11-arm
    defaults:
      run:
        # Forces GitHub Actions to run commands inside the MSYS2 environment
        shell: msys2 {0} 
        
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Setup MSYS2 CLANGARM64
        uses: msys2/setup-msys2@v2
        with:
          msystem: CLANGARM64
          update: true
          # Packages to install: Toolchain + GCC wrappers
          install: >-
            mingw-w64-clang-aarch64-toolchain
            mingw-w64-clang-aarch64-gcc-compat
            mingw-w64-clang-aarch64-gmp 
            mingw-w64-clang-aarch64-mpfr 
            mingw-w64-clang-aarch64-mpc
            make
            git

      - name: Verify Compiler
        run: |
          # These are actually clang wrappers, but accept standard GCC flags
          gcc --version
          g++ --version
          echo "Target Architecture:"
          gcc -dumpmachine
          

      - name: Configure and Build
        shell: msys2 {0}
        run: |
          # cd libgfortran
          ./configure \
          --host=aarch64-w64-mingw32 \
          --target=aarch64-w64-mingw32 \
          --build=aarch64-w64-mingw32 \
          --enable-languages=c,c++ \
          --disable-bootstrap \
          --disable-multilib
          make MAKEINFO=missing STAGE1_CFLAGS="-D__USE_MINGW_ACCESS" all
      # 5. Example B: Upload a specific file with custom retention
      - name: Upload Build Dir
        uses: actions/upload-artifact@v7
        with:
          name: build-dir-archive
          path: ./
          retention-days: 1
